import { theme } from '@/tokens/theme';
import { StyleSheet } from 'react-native';

export const analyticsChartStyles = StyleSheet.create({
  panel: { gap: theme.spacing.lg },
  panelHeader: { gap: theme.spacing.xs },
  panelTitle: { textAlign: 'left' },
  panelBody: { width: '100%' },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: theme.spacing.xxl,
    gap: theme.spacing.sm,
  },
  emptyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.sm,
    borderRadius: theme.borderRadius.full,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  emptyMessage: { textAlign: 'center', maxWidth: 240 },
  series: { gap: theme.spacing.md },
  seriesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: theme.spacing.sm,
  },
  seriesSummary: { flex: 1, minWidth: 0, gap: 3 },
  seriesControls: { flexDirection: 'row', gap: 2 },
  seriesControl: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: theme.borderRadius.md,
    backgroundColor: theme.colors.secondary,
  },
  plotRow: { flexDirection: 'row', gap: theme.spacing.sm },
  yAxis: {
    width: 29,
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingVertical: 1,
  },
  plot: { flex: 1, minWidth: 0, minHeight: 44 },
  axisLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingLeft: 37,
    gap: theme.spacing.md,
  },
  breakdownList: { gap: theme.spacing.xl },
  breakdownRow: { gap: theme.spacing.sm },
  breakdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: theme.spacing.md,
  },
  breakdownTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: theme.spacing.sm,
    flex: 1,
    minWidth: 0,
  },
  breakdownTitle: { flexShrink: 1, lineHeight: 22 },
  breakdownMetric: { textAlign: 'right', minWidth: 64 },
  breakdownSwatch: {
    width: 7,
    height: 7,
    borderRadius: theme.borderRadius.full,
    marginTop: 7,
  },
  breakdownTrack: {
    width: '100%',
    height: 5,
    borderRadius: theme.borderRadius.full,
    overflow: 'hidden',
    backgroundColor: theme.colors.secondary,
  },
  breakdownFill: { height: '100%', borderRadius: theme.borderRadius.full },
});
