import {
  Album,
  BookOpen,
  ChartColumn,
  ChartColumnIncreasing,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleX,
  Clock3,
  CloudOff,
  Crosshair,
  Flag,
  Flame,
  GraduationCap,
  Hourglass,
  Info,
  Layers2,
  Library,
  Lightbulb,
  LoaderCircle,
  Medal,
  Plus,
  PlusCircle,
  Ribbon,
  Search,
  Settings,
  Sparkles,
  Star,
  Timer,
  Trophy,
  User,
  Users,
  X,
  Zap,
} from 'lucide-react-native';
import type { LucideIconComponent } from './types';

export const iconRegistry = {
  albums: Album,
  book: BookOpen,
  chart: ChartColumn,
  check: Check,
  checkCircle: CircleCheck,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  cloudOff: CloudOff,
  close: X,
  closeCircle: CircleX,
  crosshair: Crosshair,
  flag: Flag,
  flash: Zap,
  flame: Flame,
  graduationCap: GraduationCap,
  hourglass: Hourglass,
  information: Info,
  layers: Layers2,
  library: Library,
  lightbulb: Lightbulb,
  loaderCircle: LoaderCircle,
  medal: Medal,
  people: Users,
  person: User,
  plus: Plus,
  plusCircle: PlusCircle,
  ribbon: Ribbon,
  search: Search,
  settings: Settings,
  sparkles: Sparkles,
  star: Star,
  time: Clock3,
  timer: Timer,
  trendingUp: ChartColumnIncreasing,
  trophy: Trophy,
} as const satisfies Record<string, LucideIconComponent>;

export type AppIconName = keyof typeof iconRegistry;
